[package]
name = "epgquery_port"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "epgquery_port"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
pg_parse = {path = "../pg_parse"}
